CREATE TABLE IBM_MQ_DEFINITION
(
 ID NUMBER PRIMARY KEY,
DESCRIPTION VARCHAR(5000),
DETAILS VARCHAR(5000),
IMAGE_PATHS VARCHAR(10000)
);

CREATE SEQUENCE IBM_MQ_SEQUENCE
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCACHE
NOCYCLE;